//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by gobang.rc
//
#define IDR_MENU                        101
#define IDI_ICON                        102
#define IDC_VISION                      40002
#define IDC_SERVER                      40003
#define IDC_CONNECT                     40004
#define IDC_SINGLE                      40006
#define IDC_MULTI                       40007
#define IDC_EXIT                        40008
#define IDC_ABORT                       40009
#define IDC_DOUBLE                      40010
#define IDC_RESET                       40011
#define IDC_RESTORATION                 40013

#define IDC_WHITE                       40021
#define IDC_BLACK                       40022
#define IDC_BENCHMARK                   40032

#define IDC_LEVELEASY                   50006
#define IDC_LEVELSTANDARD                50008
#define IDC_LEVELHARD                   50010
// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40012
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
